package format

import (
	"fmt"
	"strings"

	"github.com/narrowcastdev/dota-meta/internal/analysis"
)

// FormatReddit generates a Reddit-formatted markdown post from the analysis.
func FormatReddit(result analysis.FullAnalysis, date string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## [Weekly] Heroes that are secretly broken at your rank -- Week of %s\n\n", date)
	fmt.Fprintf(&b, "Data from OpenDota (%s picks analyzed). Heroes need 1000+ picks to qualify.\n\n", formatNumber(result.TotalMatches))

	b.WriteString("### Best heroes by bracket this week\n\n")
	for _, ba := range result.Brackets {
		fmt.Fprintf(&b, "**%s:**\n\n", ba.Pair.Name)
		if len(ba.Best) == 0 {
			b.WriteString("No heroes qualified.\n\n")
			continue
		}
		b.WriteString("| Hero | Win Rate | Pick Rate |\n")
		b.WriteString("|------|----------|----------|\n")
		for _, s := range ba.Best {
			fmt.Fprintf(&b, "| %s | %.1f%% | %.1f%% |\n", s.Hero.LocalizedName, s.WinRate, s.PickRate)
		}
		b.WriteString("\n")
	}

	b.WriteString("### Sleeper picks (high WR, low pick rate at your bracket)\n\n")
	for _, ba := range result.Brackets {
		fmt.Fprintf(&b, "**%s:** ", ba.Pair.Name)
		if len(ba.Sleepers) == 0 {
			b.WriteString("None this week.\n\n")
			continue
		}
		parts := make([]string, len(ba.Sleepers))
		for i, s := range ba.Sleepers {
			parts[i] = fmt.Sprintf("%s (%.1f%%, only %.1f%% pick rate)", s.Hero.LocalizedName, s.WinRate, s.PickRate)
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	b.WriteString("### Trap picks (popular but losing at your bracket)\n\n")
	for _, ba := range result.Brackets {
		fmt.Fprintf(&b, "**%s:** ", ba.Pair.Name)
		if len(ba.Traps) == 0 {
			b.WriteString("None this week.\n\n")
			continue
		}
		parts := make([]string, len(ba.Traps))
		for i, s := range ba.Traps {
			parts[i] = fmt.Sprintf("%s (%.1f%% pick rate, only %.1f%% WR)", s.Hero.LocalizedName, s.PickRate, s.WinRate)
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	b.WriteString("### Bracket delta: heroes that play differently across ranks\n\n")

	b.WriteString("**Low bracket stompers** (much higher WR in Herald-Guardian than Divine-Immortal):\n\n")
	if len(result.LowStompers) == 0 {
		b.WriteString("None this week.\n\n")
	} else {
		b.WriteString("| Hero | Herald-Guardian WR | Divine-Immortal WR | Difference |\n")
		b.WriteString("|------|-------------------|-------------------|------------|\n")
		for _, d := range result.LowStompers {
			fmt.Fprintf(&b, "| %s | %.1f%% | %.1f%% | +%.1f%% |\n", d.Hero.LocalizedName, d.LowWR, d.HighWR, d.Delta)
		}
		b.WriteString("\n")
	}

	b.WriteString("**High skill ceiling** (much higher WR in Divine-Immortal than Herald-Guardian):\n\n")
	if len(result.HighSkillCap) == 0 {
		b.WriteString("None this week.\n\n")
	} else {
		b.WriteString("| Hero | Herald-Guardian WR | Divine-Immortal WR | Difference |\n")
		b.WriteString("|------|-------------------|-------------------|------------|\n")
		for _, d := range result.HighSkillCap {
			fmt.Fprintf(&b, "| %s | %.1f%% | %.1f%% | +%.1f%% |\n", d.Hero.LocalizedName, d.LowWR, d.HighWR, -d.Delta)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*Full interactive data with all brackets: [narrowcastdev.github.io/dota-meta](https://narrowcastdev.github.io/dota-meta)*\n\n")
	b.WriteString("*Data from [OpenDota](https://www.opendota.com). Generated by [dota-meta](https://github.com/narrowcastdev/dota-meta).*\n")

	return b.String()
}

func formatNumber(n int) string {
	if n < 1000 {
		return fmt.Sprintf("%d", n)
	}

	s := fmt.Sprintf("%d", n)
	var result strings.Builder
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			result.WriteRune(',')
		}
		result.WriteRune(c)
	}
	return result.String()
}
